# -*- coding: utf-8 -*-
"""Py_Gamezone.ipynb

Automatically generated by Colaboratory.

Original file generated by Sakib Ali Choudhary
"""

#@title Cafeteria

def cafeteria(user_points):
  menu = {"FriedRice":30,"Fries":40,"Pasta":50,"Chips":30,"SoftDrink":10}

  print("Welcome To ")
  print()
  print("Here is the menu")
  for i,j in menu.items():
    print(i,"and its price",j)
  print()
  j = 1
  for i in menu.keys():
    print("Press",j,"for ",i)
    j += 1

  print()
  print("We will Start taking your order")
  print("You may press 0 for quiting")

  def order_list(d1):
    for i,j in d1.items():
      if i == 1:
        print('FriedRice in',j,"quantity")
      elif i == 2:
        print("Fries in",j,"quantity")
      elif i == 3:
        print("Pasta",j,"quantity")
      elif i == 4:
        print("Chips",j,"quantity")
      elif i == 5:
        print("SoftDrink",j,"quantity")


  d1 = {}

  while True:
    print()
    user_input_choice = int(input("Enter Your choice "))
    if user_input_choice == 0 or user_input_choice == ""  :
      print()
      order_list(d1)
      print()
      print("Do you want to edit your order")
      print("Yes for editing or No for exiting")
      print()
      user_last_input = input("Enter Your choice ")
      user_last_input.lower()
      if user_last_input == "no" or user_last_input =="": 
        break
      elif user_last_input == "yes" or user_last_input !="" or user_last_input!="no" :
        user_input_choice = int(input("Enter Your choice "))
        if user_input_choice == 0 or user_input_choice == ""  :
          break
        user_input_quantity = int(input("Enter no of quantity "))
        if user_input_quantity == 0 or user_input_quantity == "":
          user_input_quantity = 1
        d1[user_input_choice] = user_input_quantity
      else:
        print("invalid")

    else:  
      user_input_quantity = int(input("Enter no of quantity "))
      if user_input_quantity == 0 or user_input_quantity == "":
        user_input_quantity = 1
      d1[user_input_choice] = user_input_quantity


  cart = []
  price = []


  for i,j in d1.items():
    if i == 1:
      cart.append('FriedRice')
      price.append(menu['FriedRice']*j)
    elif i == 2:
      cart.append("Fries")
      price.append(menu["Fries"]*j)
    elif i == 3:
      cart.append("Pasta")
      price.append(menu["Pasta"]*j)
    elif i == 4:
      cart.append("Chips")
      price.append(menu["Chips"]*j)
    elif i == 5:
      cart.append("SoftDrink")
      price.append(menu["SoftDrink"]*j)
  
  finalprice = sum(price)
  if user_points >= finalprice:
    print()
    print("Order invoice ")
    print()
    order_list(d1)
    print("Your final total is ",finalprice,"points")
    print("Deducted Point ",finalprice)
    print()
    print("Remaining Points are",user_points-finalprice)
    return user_points-finalprice
  else:
    print("Insufficiant balance")
    return user_points

#@title Flames
def flames():
  bn = input("Enter Name: ").lower() 
  gn = input("Enter Name: ").lower() 
  
  for i in bn: 
      if i in gn: 
          bn = bn.replace(i,"",1) 
          gn = gn.replace(i,"",1) 

  uc = len(bn+gn) 
  
  x = "FLAMES" 
  print("Unique Count: {}".format(uc)) 
  
  while len(x) > 1: 
      mod = int(uc) % len(x) 
      l = x[:(mod-1)] 
      r = x[mod:] 
      if (mod==0): 
          r = r.replace(r,"") 
          x = x.replace(x,(r+l)) 
      else: 
          x = x.replace(x,(r+l)) 

  flames_dict = {"F":"Friend","L":"Love","A":"Affection","M":"Marriage","E":"Enemy","S":"Sibling"}
  print("The Relationship between them is {}".format(flames_dict[x]))

  return user_points

#@title Rock Paper Scissors 
import random

def rps(user_points):
  computerl = ["rock","paper","scissors"]
  computer_choice = computerl[random.randint(0,len(computerl)-1)]
  computer_choice

  print("Welcome to Rock Paper Sissors")
  print("Computer Vs User")
  print()
  print("Press r for Rock")
  print("Press p for Paper")
  print("Press s for Scissors")
  print()
  user_intput = input("Enter your choice ")
  user_intput = user_intput.lower() 
  print()
  print(f"The Computer Entered {computer_choice}")
  print()

  if (computer_choice == "rock" and user_intput=="r") or (computer_choice == "paper" and user_intput=="p") or computer_choice == "sissors" and user_intput=="s":
    print("Tie")
  elif (computer_choice == "rock" and user_intput == "p") or (computer_choice == "paper" and user_intput == "r"):
    if computer_choice == "rock":
      print("User Won")
      user_points +=20
    else:
      print("Computer Won")
  elif (computer_choice == "rock" and user_intput == "s") or (computer_choice == "scissors" and user_intput == "r"):
    if computer_choice == "scissors":
      print("User Won")
      user_points +=20
    else:
      print("Computer Won")
  elif (computer_choice == "paper" and user_intput == "s") or (computer_choice == "scissors" and user_intput == "p"):
    if computer_choice == "paper":
      print("User Won")
      user_points +=20
    else:
      print("Computer Won")
  else:
    print("Invalid")
    print("Computer Won by Default")

  return user_points

#@title Guess The Movie
def movie(user_points):
  movie_list = ["3idiots","Pathan","Baahubali","Dangal","KGF"]
  movie = movie_list[random.randint(0,len(movie_list)-1)]
  movie = movie.lower()
  movie = movie.replace(" ","")

  l1 = []
  for i in (movie):
    l1.append(i)

  l2 = []
  for i in range(len(movie)):
    l2.append("*")
  l = 0
  flag = 0

  while True:
    if flag == 3:
      print("You have lost all the chances")
      break

    print()
    print(l2)
    print()

    option = input("Enter your guess ")
    option = option.lower()
    if option == 0:
      print("Invalid")
      break

    if option not in l1:
      flag = flag +1
    
    if option in l1:
      count_occ = l1.count(option)
      for i in range(count_occ):
        indexofl1 = l1.index(option)
        while True:
          l1[indexofl1] = 0
          break
        l2[indexofl1] = option
    
    if "*" not in l2:
      print()
      print(l2)
      print("Congratulation!!")
      print("You did it!!")
      user_points += 20
      break
  return user_points

#@title Snake And Ladder
def snakeandladder(user_points):
  def rolldice():
    num = random.randint(1,6)
    return num 

  snake_ladder={1:38,4:14,8:10,21:42,28:74,50:67,71:92,80:99,97:78,95:56,88:24,62:18,36:6,48:26,32:10}
  position = 0
  position1 = 0
  round = 0
  print("Welcome to Snake and Ladder ")
  while True:
    if position == 100:
      print("User is Winner ")
      user_points += 20
      break
    elif position1 ==100:
      print("Computer is Winner ")
      break
    else:
      if round%2 ==0 :
        round += 1
        print()
        print("User")
        print()
        print("Press 1 to roll the dice")
        user_input = int(input("Enter your choice "))
        print()
        if user_input == 1:
          dicenum = rolldice()
          print("The dice has shown ",dicenum)
          position += dicenum
          if position > 100:
            position -= dicenum
        else:
          print("Invalid choice")

        print("User is currently in ",position,"position")
        for i,j in snake_ladder.items():
          if position == i:
            position1 = j
      else :
        round +=1
        print()
        print("Computer")
        print()
        dicenum = rolldice()
        print("The dice for computer has shown ",dicenum)
        position1 += dicenum
        if position1 > 100:
          position1 -= dicenum

        print("Computer is currently in ",position1,"position")
        for i,j in snake_ladder.items():
          if position1 == i:
            position1 = j
  
  return user_points

#@title Tic Tac Toe

def tictactoe(user_points):

  possibleNumbers = [1,2,3,4,5,6,7,8,9]
  gameBoard = [[1,2,3], [4,5,6], [7,8,9]]
  rows = 3

  def printGameBoard():
    for x in range(rows):
        print(gameBoard[x],end = '\n')

  def modifyArray(num, turn):
    num -= 1
    if(num == 0):
      gameBoard[0][0] = turn
    elif(num == 1):
      gameBoard[0][1] = turn
    elif(num == 2):
      gameBoard[0][2] = turn
    elif(num == 3):
      gameBoard[1][0] = turn
    elif(num == 4):
      gameBoard[1][1] = turn
    elif(num == 5):
      gameBoard[1][2] = turn
    elif(num == 6):
      gameBoard[2][0] = turn
    elif(num == 7):
      gameBoard[2][1] = turn
    elif(num == 8):
      gameBoard[2][2] = turn

  def checkForWinner(gameBoard):
    if(gameBoard[0][0] == 'X' and gameBoard[0][1] == 'X' and gameBoard[0][2] == 'X'):
      print("X has won!")
      return "X"
    elif(gameBoard[0][0] == 'O' and gameBoard[0][1] == 'O' and gameBoard[0][2] == 'O'):
      print("O has won!")
      return "O"
    elif(gameBoard[1][0] == 'X' and gameBoard[1][1] == 'X' and gameBoard[1][2] == 'X'):
      print("X has won!")
      return "X"
    elif(gameBoard[1][0] == 'O' and gameBoard[1][1] == 'O' and gameBoard[1][2] == 'O'):
      print("O has won!")
      return "O"
    elif(gameBoard[2][0] == 'X' and gameBoard[2][1] == 'X' and gameBoard[2][2] == 'X'):
      print("X has won!")
      return "X"
    elif(gameBoard[2][0] == 'O' and gameBoard[2][1] == 'O' and gameBoard[2][2] == 'O'):
      print("O has won!")
      return "O"

    if(gameBoard[0][0] == 'X' and gameBoard[1][0] == 'X' and gameBoard[2][0] == 'X'):
      print("X has won!")
      return "X"
    elif(gameBoard[0][0] == 'O' and gameBoard[1][0] == 'O' and gameBoard[2][0] == 'O'):
      print("O has won!")
      return "O"
    elif(gameBoard[0][1] == 'X' and gameBoard[1][1] == 'X' and gameBoard[2][1] == 'X'):
      print("X has won!")
      return "X"
    elif(gameBoard[0][1] == 'O' and gameBoard[1][1] == 'O' and gameBoard[2][1] == 'O'):
      print("O has won!")
      return "O"
    elif(gameBoard[0][2] == 'X' and gameBoard[1][2] == 'X' and gameBoard[2][2] == 'X'):
      print("X has won!")
      return "X"
    elif(gameBoard[0][2] == 'O' and gameBoard[1][2] == 'O' and gameBoard[2][2] == 'O'):
      print("O has won!")
      return "O"

    elif(gameBoard[0][0] == 'X' and gameBoard[1][1] == 'X' and gameBoard[2][2] == 'X'):
      print("X has won!")
      return "X"
    elif(gameBoard[0][0] == 'O' and gameBoard[1][1] == 'O' and gameBoard[2][2] == 'O'):
      print("O has won!")  
      return "O"
    elif(gameBoard[0][2] == 'X' and gameBoard[1][1] == 'X' and gameBoard[2][0] == 'X'):
      print("X has won!")  
      return "X"
    elif(gameBoard[0][2] == 'O' and gameBoard[1][1] == 'O' and gameBoard[2][0] == 'O'):
      print("O has won!") 
      return "O" 
    else:
      return "N"

  flag = 0
  turnCounter = 0
  while True:
    if flag == 1:
      break
    if(turnCounter % 2 == 0):
      printGameBoard()
      print("User is X")
      print("Computer is O")
      numberPicked = int(input("\nChoose a number [1-9]: "))
      if numberPicked in possibleNumbers:
        if(numberPicked >= 1 and numberPicked <= 9):
          modifyArray(numberPicked, 'X')
          possibleNumbers.remove(numberPicked)
        else:
          print("Invalid input. Please try again.")
        turnCounter += 1
      else:
        print("Invalid input. Please try again")
    else:
      while(True):
        computer = random.choice(possibleNumbers)
        print("\nCpu choice: ", computer)
        if(computer in possibleNumbers):
          modifyArray(computer, 'O')
          possibleNumbers.remove(computer)
          turnCounter += 1
          break
    
    winner = checkForWinner(gameBoard)
    if winner == "N" and len(possibleNumbers) == 0 :
      print("Tie")
      break
    if(winner != "N"):
      print("\nGame over! Thank you for playing :)")
      if winner == "X":
        user_points +=20
      break
  return user_points

#@title Main

if __name__ == "__main__":
  user_points = 500
  while True:
    if user_points<= 0:
      break
    if user_points<30:
      print("Low Balance You can access cafeteria only")
    print()
    print("Welcome To Gamezone")
    print()
    print("Press 1 for Cafeteria")
    print("Press 2 for Flames")
    print("Press 3 for Rock Paper Scissors")
    print("Press 4 for Guess The Movie")
    print("Press 5 for Snake And Ladder")
    print("Press 6 for Tic Tac Toe")
    print("Press 0 To Exit")
    print()
    user_option = input("Enter Your Choice ")
    if user_option == "0":
      break
    elif user_option == "1":
      print("You have ",user_points,"points")
      print("Do you want to continue to go to Cafeteria portal ")
      print("Yes/No")
      print()
      user_confirm = input("Enter your choice ")
      user_confirm = user_confirm.lower()
      if user_confirm ==  "yes":
        userpoints = cafeteria(user_points)
      elif user_confirm == "no" or user_confirm == "":
        continue
      else:
        print("Invalid Entry")
    elif user_option == "2" and user_points >= 30 :
      print("You have ",user_points,"points")
      print("Do you want to continue to go to Flames portal ")
      print("It will cost you 30 points")
      print("Yes/No")
      print()
      user_confirm = input("Enter your choice ")
      user_confirm = user_confirm.lower()
      if user_confirm ==  "yes":
        user_points -= 30 
        user_points = flames()
      elif user_confirm == "no" or user_confirm == "":
        continue
      else:
        print("Invalid Entry")
    elif user_option == "3" and user_points>=30:
      print("You have ",user_points,"points")
      print("Do you want to continue to go to Rock Paper Scissors portal ")
      print("It will cost you 30 points")
      print("Yes/No")
      print()
      user_confirm = input("Enter your choice ")
      user_confirm = user_confirm.lower()
      if user_confirm ==  "yes":
        user_points -= 30 
        user_points = rps(user_points)
      elif user_confirm == "no" or user_confirm == "":
        continue
      else:
        print("Invalid Entry")
    elif user_option == "4" and user_points>=30:
      print("You have ",user_points,"points")
      print("Do you want to continue to go to Guess The Movies portal ")
      print("It will cost you 30 points")
      print("Yes/No")
      print()
      user_confirm = input("Enter your choice ")
      user_confirm = user_confirm.lower()
      if user_confirm ==  "yes":
        user_points -= 30 
        user_points = movie(user_points)
      elif user_confirm == "no" or user_confirm == "":
        continue
      else:
        print("Invalid Entry")
    elif user_option == "5" and user_points>=30:
      print("You have ",user_points,"points")
      print("Do you want to continue to go to Snake And Ladder portal ")
      print("It will cost you 30 points")
      print("Yes/No")
      print()
      user_confirm = input("Enter your choice ")
      user_confirm = user_confirm.lower()
      if user_confirm ==  "yes":
        user_points -= 30 
        user_points = snakeandladder(user_points)
      elif user_confirm == "no" or user_confirm == "":
        continue
      else:
        print("Invalid Entry")
    elif user_option == "6" and user_points>=30:
      print("You have ",user_points,"points")
      print("Do you want to continue to go to Tic Tac Toe portal ")
      print("It will cost you 30 points")
      print("Yes/No")
      print()
      user_confirm = input("Enter your choice ")
      user_confirm = user_confirm.lower()
      if user_confirm ==  "yes":
        user_points -= 30 
        user_points = tictactoe(user_points)
      elif user_confirm == "no" or user_confirm == "":
        continue
      else:
        print("Invalid Entry")
    else:
      print("Invalid choice")
      print("Please enter again")
